<?xml version="1.0" encoding="UTF-8" standalone="no"?><testsuite errors="0" failures="1" name="Sign up Function" skipped="0" tests="6" time="91.64" timestamp="2023-05-24 08:45:43"><testcase name="Confirm user can sign up successfully with valid username and valid password."><failure message="expected [Sign up successful.] but found [This user already exist.]" type="java.lang.AssertionError">expected [Sign up successful.] but found [This user already exist.]</failure><system-err>expected [Sign up successful.] but found [This user already exist.]&#13;
step_cucumberSignup.SignUpSteps.confirmMessage(SignUpSteps.java:39)&#13;
✽.Display message "Sign up successful."(file:///D:/download/ân/CaseStudySelenium_TranNNH/src/test/resources/feature/signUp.feature:7)&#13;
</system-err></testcase><testcase name="Confirm user can not sign up successfully."/><testcase name="Confirm user can not sign up successfully when username already exist and password is filled in."/><testcase name="Confirm user can close sign up dialog when clicking on the close button."/></testsuite>